# Example configuration file for prometheus-yt-exporter
# You can override any value by setting it here.
# If a value is set both in the environment and in this file, the config file takes precedence.

youtube_api_key: "your-api-key-here"
youtube_video_id: "your-video-id-here"
scrape_interval_seconds: 30
